language: python
python:
  - '2.7'
install:
  - pip install -r requirements.txt
  - pip install coveralls pytest-cov

script: py.test --cov-report term-missing --cov flask_api_awesomesauce

after_success: coveralls

deploy:
  provider: pypi
  user: eikonomega
  server: http://pypi.python.org/pypi
  password:
    secure: ddA2GEhOsG8Z6KBssW3Mx2qWJ2HxGYDtjpQgvr7l2lizli12UFmtl1CllBaXNB9iZgTYm8g7a2eM73QQU0whkeWGecb233wRLJjUYjQmIv3kZRLkvmWopEYY9iwqyASSvY8ykmU6o3JNCfRvQ5bZw+mDVROs6ldJXYlw/6A6hhM=
  on:
    repo: eikonomega/flask-api-awesomesauce
